name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag  mveyone/Docker-imgage-auto-build:latest
    -  name: Push the docker image
       run: docker login -u mveyone -p ${{ secrets.DOCKER_TOKEN }} && docker push mveyone/Docker-imgage-auto-build:latest
